#!/bin/bash
: ${DIALOG_OK=0}

# Duplicate file descriptor 1 on descriptor 3
exec 3>&1

# Get all branches
branches=($(git branch | grep "^[^*]"))

# Create params
i=0
params=""

for branch in ${branches[@]};do
  params="$params $i $branch"
  ((i=i+1))
done

# Show dialog
name=$(dialog --clear --title "Available branches" --menu choose 15 100 10 $params 2>&1 1>&3)
ret=$?

# Close file descriptor 3
exec 3>&-

clear

if [ $ret = $DIALOG_OK ]
then
  echo switching to branch ${branches[$name]}
  git checkout ${branches[$name]}
fi
