#!/bin/bash

branches=($(git branch | grep "^[^*]"))

i=0
params=""

for branch in ${branches[@]};do
  params="$params $i $branch"
  ((i=i+1))
done

res="dialog --clear --menu choose 15 50 4  $params"

selection="$res 2>&1 1>&3"
exec 3>&1
branchName=`eval $selection`
exec 3>&-
clear

git checkout ${branches[$branchName]}
